/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_logitow_bleapi_LogitowBleControl */

#ifndef _Included_com_logitow_bleapi_LogitowBleControl
#define _Included_com_logitow_bleapi_LogitowBleControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_logitow_bleapi_LogitowBleControl
 * Method:    bleInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_logitow_bleapi_LogitowBleControl_bleInit
  (JNIEnv *, jobject);

/*
 * Class:     com_logitow_bleapi_LogitowBleControl
 * Method:    getBleStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_logitow_bleapi_LogitowBleControl_getBleStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_logitow_bleapi_LogitowBleControl
 * Method:    startSearchBle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_logitow_bleapi_LogitowBleControl_startSearchBle
  (JNIEnv *, jobject);

/*
 * Class:     com_logitow_bleapi_LogitowBleControl
 * Method:    connectDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_logitow_bleapi_LogitowBleControl_connectDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
